apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: enthusiastic-rat-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: enthusiastic-rat-python 
  name: enthusiastic-rat-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: enthusiastic-rat-python 
